# Generated by Django 2.2.8 on 2020-07-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('pdf_copy', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=1000)),
                ('item_quantity', models.IntegerField()),
                ('item_rate', models.FloatField()),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceSystem.Invoices')),
            ],
        ),
    ]
