# Generated by Django 2.2.8 on 2020-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofitems',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
